### ISSUE TITLE
Please document why the library wants Python >= 3.7.

### ISSUE THREAD

**Issue by socketpair** [ccxtechnologies/adbus#39]
Can I use Python 3.5.4 actually ?

**Comment by refi64** [comment]
I believe it uses variable annotations which are 3.7+ only.

**Comment by Kaveshnikov** [comment]
But in fact, I have no syntax errors in Python 3.6

**Comment by charleseidsness** [comment]
It will most likely work in Python 3.6, but all development and testing is using 3.7, we don't officially support any versions pre-3.7.

**Comment by socketpair** [comment]
I would recommend you to support Python 3.6 since 3.7 is too new for current LTS OSes.

**Comment by charleseidsness** [comment]
Good point, if someone uses this library for an application that is based on 3.6, and does some testing on 3.6 we'd be happy to update the minimum version requirements. We exclusively use 3.7 so aren't able to easily verify that there aren't issues using 3.6.
