### ISSUE TITLE
NoReply: Method call timed out

### ISSUE THREAD

**Issue by Kavan72** [ccxtechnologies/adbus#50]
i think, you have to give timeout support on  `await proxy.update()`. cuz why we wait 120 sec when we dont have proxy obj
like this 
```
service = adbus.Service(bus='session')
proxy = await adbus.client.Proxy(service, bus_name, '/com/example/Service1',
                                   interface='com.example.service.unit').update(timeout_ms=5000)
```

**Comment by Kavan72** [comment]
@charleseidsness are you here ?

**Comment by charleseidsness** [comment]
It's not a bad idea, we'll have a look at implementing it in a few days.

**Comment by charleseidsness** [comment]
I just checked in an update that adds an optional timeout_ms to update, it also returns its self so that you can use that single line syntax in your example.

**Comment by Kavan72** [comment]
```py
adbus.sdbus.SdbusError: org.freedesktop.DBus.Error.NoReply: Method call timed out
```
maybe, you are missing something. cuz it's still waiting 120 sec (that is by default on dbus) i think you have to raise custom timeout error if no update

**Comment by Kavan72** [comment]
something like this ```await asyncio.wait_for(call.event.wait(), int(5)) ``` in call.py

**Comment by Kavan72** [comment]
@charleseidsness sir, am i right ?

**Comment by charleseidsness** [comment]
You're going to have to be more specific, can you send the error that is raised, including the traceback?

**Comment by Kavan72** [comment]
```py
Fri Jul 19 18:12:41 2019
Start_time_in_call_dbus =>  Fri Jul 19 18:12:41 2019
Start_time_in_Scall =>  Fri Jul 19 18:12:41 2019
Stop_time_in_Scall =>  Fri Jul 19 18:12:41 2019

Ignoring exception in command test:
Traceback (most recent call last):
  File "/media/kavan/DATA/discord_bots/wfbot/venv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/media/kavan/DATA/discord_bots/wfbot/test/test_bot.py", line 38, in test
    await proxy.update(timeout_ms=5000)
  File "/media/kavan/DATA/discord_bots/wfbot/venv/lib/python3.7/site-packages/adbus/client/proxy.py", line 477, in update
    timeout_ms=timeout_ms,
  File "/media/kavan/DATA/discord_bots/wfbot/venv/lib/python3.7/site-packages/adbus/client/call.py", line 59, in call
    raise call.response
  File "adbus/sdbus/call.pxi", line 14, in adbus.sdbus.call_callback
  File "adbus/sdbus/message.pxi", line 32, in adbus.sdbus.Message.import_sd_bus_message
adbus.sdbus.SdbusError: org.freedesktop.DBus.Error.NoReply: Method call timed out
```

this is full traceback which is i got

**Comment by charleseidsness** [comment]
We're not able to replicate this, it's working for us

That timeout is actually returned from the systemd dbus library, which will
be set to 5 seconds using the latest version in git.

You're free to add an additional timeout to your own code.

==
Charles Eidsness
Chief Engineer
*CCX Technologies*
(613)791-9715

**Comment by Kavan72** [comment]
ok np i will fork and edit it for me :smiley:

**Comment by charleseidsness** [comment]
Sounds good!

==
Charles Eidsness
Chief Engineer
*CCX Technologies*
(613)791-9715

**Comment by Kavan72** [comment]
when you free check this https://github.com/Kavan72/adbus/commit/cc234531889bd1e2d726bd1a41d531a9e30b5cb7

**Comment by charleseidsness** [comment]
I'd prefer to try to figure out why the dbus time out isn't working in your
case, and only add that extra timeout as a last resort.

We can have another look in a couple of weeks, once we have more time.


==
Charles Eidsness
Chief Engineer
*CCX Technologies*
(613)791-9715
