### ISSUE TITLE
`depreciated` and `deprectiated` parameters/properties should be spelled `deprecated`

### ISSUE THREAD

**Issue by sth** [ccxtechnologies/adbus#53]
Several classes have a `depreciated` or `deprectiated` constructor parameter and property. It should be spelled `deprecated`, like the underlying DBus property `SD_BUS_VTABLE_DEPRECATED`.

The easiest fix would be to just rename the parameters/properties.

If you want to stay backwards compatible with people using the old names you could also add keyword-only parameters with the old spellings, like for example in `adbus/server/signal.py`:

```python
def __init__(
    self, name=None, deprecated=False, hidden=False, camel_convert=True,
    *, deprectiated=False
):
    self.deprecated = self.deprectiated = deprecated or deprectiated
    ...
```

**Comment by sth** [comment]
I could write a pull request fixing this, one way or the other.

**Comment by charleseidsness** [comment]
A pull request would be great, you can just fix the spelling, a global replace shouldn't be too tough for folks.

Thanks!
