### ISSUE TITLE
Active Listen object is garbage collected

### ISSUE THREAD

**Issue by sth** [ccxtechnologies/adbus#54]
When using a `adbus.client.Proxy` to listen for a signal, a `sdbus.Listen` object is created. As long as that object exists the signal is received. When the Proxy goes out of scope the Listen object can be garbage collected, which will stop receiving of the signal.

This can be quite confusing because a because things might seem to work for a while before "randomly" stopping.

For example the following setup function works and `watcher` will be called when signals arrive, but only until garbage collection:

```python
async def setup(watcher):
    service = adbus.Service(bus='session')
    proxy = adbus.client.Proxy(service, 'org.freedesktop.ScreenSaver', '/ScreenSaver')
    await proxy.update()
    proxy.ActiveChanged.add(watcher)
```

Some ideas how that could be improved:
- Emit a warning when a Proxy with active listeners gets destroyed
- Keep the Listen object alive even after the Proxy gets garbage collected
- Use a context manager when listening for signals so it's clear when the signal listener goes out of scope

**Comment by charleseidsness** [comment]
You're right, that could be confusing for people. I think adding a warning would be sufficient, the other two ideas may have unexpected consequences for current users of this library.

Would you be able to create a Pull Request for this one too? If not we can have a look at adding a warning next week.

**Comment by sth** [comment]
It turns our even a simple warning would be quite an invasive change.

For the warning to be useful, intentional deletions need to be distinguished from "accidental" deletions. That means there needs to be some `close()` method or something that will be called when the owner of the `Listen` is done with it. In `Signal` that would for example be in `remove()`, when a listener is removed.

But I suspect that most code currently doesn't explicitly remove the listeners when a `Signal` goes out of scope. In such a case it is generally not clear if the surrounding code expects the handler function to stop being called or continue to be called. (The actual behaviour that it's called for a while and then stops is probably unexpected for both.)

This problem also applies to anything that might contain a `Signal` or `Listen`, like `Proxy` and even `Interface`. The only solution I see is to add some `close()` function to all those objects and require it to be called when the owner is done with it. Calling all those `close()` functions would of course require a lot of changes in code that uses the library...

**Comment by charleseidsness** [comment]
We wouldn't want to add that, we use this library within our own system software. We are aware of this limitation and keep proxy in scope for as long as we need to receive signals.

Maybe a not in the readme is the best we can do. I'll add one.
