### ISSUE TITLE
travis integration is broken

### ISSUE THREAD

**Issue by jameshilliard** [ccxtechnologies/adbus#63]
Seems the Travis github integration is broken as recent pull requests/commits don't seem to show test status anymore.

Travis probably just needs to be [migrated](https://docs.travis-ci.com/user/migrate/open-source-repository-migration) from the old `.org` address to the new `.com` address.

**Comment by charleseidsness** [comment]
Travis is running and passed (from the travis.org console), is this maybe related to the recent GitHub GUI updates?

**Comment by charleseidsness** [comment]
I don't think I understand the issue, the [Travis Page](https://travis-ci.org/github/ccxtechnologies/adbus) is updating and so is the little icon in the readme.

**Comment by jameshilliard** [comment]
I mean, it's not syncing the status to github commits and pull requests.

**Comment by jameshilliard** [comment]
Well not reliably at least, I see some pull requests it's getting run on but [recent commits](https://github.com/ccxtechnologies/adbus/commits/master) don't have the green check like they are supposed to. Usually switching to the new `.com` version fixes it.

**Comment by charleseidsness** [comment]
Okay, I just migrated it.
