### ISSUE TITLE
Watch signal events

### ISSUE THREAD

**Issue by laped83** [ccxtechnologies/adbus#66]
I can't find anything in the documentation on how to watch for signal event. I want a dbus service to do something when a given dbus signal is seen. Can you give an example on how this is done? :D

**Comment by laped83** [comment]
Okay i found an example in the test_client.py. So I'm closing this.

**Comment by charleseidsness** [comment]
That's great!

Sorry about the long delay (vacation). If you have anymore questions just let me know.
