### ISSUE TITLE
DepreciationWarning Python 3.8

### ISSUE THREAD

**Issue by henfredemars** [ccxtechnologies/adbus#71]
I’m reporting a depreciation warning in the hopes that it will be useful to someone else.

client/call.py:39 DepreciationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.

`call = sdbus.Call(`

**Comment by tirkarthi** [comment]
The loop argument has been removed in Python 3.10

**Comment by charleseidsness** [comment]
Thanks for the info, we didn't really need to define the loop of the Event anyways so just removed the argument.
