### ISSUE TITLE
Dbus server method with an unsigned int

### ISSUE THREAD

**Issue by laped83** [ccxtechnologies/adbus#72]
How can you create a server method with an unsigned int like uint32 or uint64? The following examples creates a signature with "i" and I wants something  like "u". 

I could send it as string value but maybe I have missed something. :D

@adbus.server.method(unprivileged=True)
def Foo(myval: int) -> bool:
    pass

**Comment by charleseidsness** [comment]
Unfortunately you can't, since Python doesn't differentiate I never added that feature.

If you have a specific use case we could have a look at it.

**Comment by laped83** [comment]
I can see in signature.pxi that all int i mapped to INT32. A quick fix could be to change this to a int64t instead? A signed 32bit is a bit limited :)

cdef bytes signature_int = int(sdbus_h.SD_BUS_TYPE_INT32).to_bytes(1, 'big')

**Comment by charleseidsness** [comment]
That would have been a better initial choice, but unfortunately I think that would break interfacing with existing systems.

The only solution that wouldn't do that; that I can think of, would be to add additional data types. We could open a ticket for that but it might be some time before I get a chance to address it.

**Comment by laped83** [comment]
Lets just close this for now. I can work around this limitation :)

**Comment by charleseidsness** [comment]
Works for me, thanks!
